#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${GREEN}==> Starting the Setup Installation...${NC}"

# 1. dependencies
echo -e "${GREEN}==> Installing packages...${NC}"
sudo pacman -S --noconfirm base-devel git \
    libx11 libxinerama libxft webkit2gtk \
    xorg-server xorg-xinit \
    alacritty \
    feh \
    picom \
    dmenu \
    network-manager-applet \
    volumeicon pavucontrol \
    pipewire pipewire-pulse pipewire-alsa \
    lxappearance papirus-icon-theme \
    ttf-jetbrains-mono-nerd terminus-font \
    htop btop scrot fastfetch \
    neovim nano

echo -e "${GREEN}==> Copying configuration files...${NC}"
mkdir -p ~/.config/alacritty
mkdir -p ~/.config/picom
mkdir -p ~/.config/fastfetch
mkdir -p ~/wallpapers

cp configs/alacritty/alacritty.toml ~/.config/alacritty/alacritty.toml
cp configs/picom/picom.conf ~/.config/picom/picom.conf
cp wallpapers/wallpaper.jpg ~/wallpapers/wallpaper.jpg

# 2. dwm
echo -e "${GREEN}==> Compiling and Installing DWM...${NC}"
sudo make clean install

# 3. Slstatus
echo -e "${GREEN}==> Downloading, installing and Setuping the Slstatus...${NC}"

DWM_DIR=$(pwd)

mkdir -p ~/suckless
cd ~/suckless

if [ -d "slstatus" ]; then
    echo "Slstatus folder found. Updating..."
    cd slstatus
    git pull
else
    echo "Cloning Slstatus..."
    git clone https://git.suckless.org/slstatus
    cd slstatus
fi

echo "Injecting custom config..."
cp "$DWM_DIR/configs/slstatus/config.h" config.h
sudo make clean install

# Return to home directory to configure dotfiles
cd $HOME

echo -e "${GREEN}==> Configuring startup files (Universal Method)...${NC}"

# -----------------------------------------------------------
# STEP A: Create .xprofile (Background apps & configurations)
# -----------------------------------------------------------
if [ -f ".xprofile" ]; then
    mv .xprofile .xprofile.bak
    echo "Backup: Existing .xprofile moved to .xprofile.bak"
fi

echo "Generating .xprofile..."
cat > .xprofile <<EOF
#!/bin/sh
# Auto-generated by install script
feh --bg-scale ~/wallpapers/wallpaper.jpg &
picom -b &
nm-applet &
volumeicon &
slstatus &
EOF


# Make it executable
chmod +x .xprofile

# -----------------------------------------------------------
# STEP B: Create .xinitrc (For 'startx' users)
# -----------------------------------------------------------
# This file will simply import .xprofile settings before launching DWM.

if [ -f ".xinitrc" ]; then
    mv .xinitrc .xinitrc.bak
    echo "Backup: Existing .xinitrc moved to .xinitrc.bak"
fi

echo "Generating .xinitrc..."
cat > .xinitrc <<EOF
#!/bin/sh
# Auto-generated by install script

# Import settings from .xprofile if it exists
# This ensures consistency between LightDM and startx sessions
[ -f \$HOME/.xprofile ] && . \$HOME/.xprofile

# Launch DWM (Must be the last command with 'exec')
exec dwm
EOF

# Make it executable
chmod +x .xinitrc

echo -e "${GREEN}==> Installation Completed Successfully!${NC}"
echo "You can now restart your system or log out."
