#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${GREEN}==> Starting the Setup Installation...${NC}"

# 1. dependencies
echo -e "${GREEN}==> Installing packages...${NC}"
sudo pacman -S --needed base-devel libx11 libxft libxinerama webkit2gtk \
    feh picom terminus-font ttf-jetbrains-mono-nerd git slstatus

# 2. dwm
echo -e "${GREEN}==> Compiling and Installing DWM...${NC}"
sudo make clean install

# 3. Slstatus
echo -e "${GREEN}==> Downloading and installing the Slstatus...${NC}"
cd ..

# Check if the folder already exists to avoid errors.
if [ -d "slstatus" ]; then
    cd slstatus
    git pull
else
    git clone https://git.suckless.org/slstatus
    cd slstatus
fi

# Compiles slstatus
sudo make clean install

# Return to home directory to configure dotfiles
cd $HOME

echo -e "${GREEN}==> Configuring startup files (Universal Method)...${NC}"

# -----------------------------------------------------------
# STEP A: Create .xprofile (Background apps & configurations)
# -----------------------------------------------------------
if [ -f ".xprofile" ]; then
    mv .xprofile .xprofile.bak
    echo "Backup: Existing .xprofile moved to .xprofile.bak"
fi

echo "Generating .xprofile..."
cat > .xprofile <<EOF
#!/bin/sh
# Auto-generated by install script

# 1. Compositor (Transparency & Shadows)
# The -b flag runs it in background (daemon mode)
picom -b &

# 2. Wallpaper (Restores the last used wallpaper)


# 3. Status Bar
slstatus &

# Add other background apps here (e.g., nm-applet &)
EOF

# Make it executable
chmod +x .xprofile

# -----------------------------------------------------------
# STEP B: Create .xinitrc (For 'startx' users)
# -----------------------------------------------------------
# This file will simply import .xprofile settings before launching DWM.

if [ -f ".xinitrc" ]; then
    mv .xinitrc .xinitrc.bak
    echo "Backup: Existing .xinitrc moved to .xinitrc.bak"
fi

echo "Generating .xinitrc..."
cat > .xinitrc <<EOF
#!/bin/sh
# Auto-generated by install script

# Import settings from .xprofile if it exists
# This ensures consistency between LightDM and startx sessions
[ -f \$HOME/.xprofile ] && . \$HOME/.xprofile

# Launch DWM (Must be the last command with 'exec')
exec dwm
EOF

# Make it executable
chmod +x .xinitrc

echo -e "${GREEN}==> Installation Completed Successfully!${NC}"
echo "You can now restart your system or log out."
